# Generated by Django 5.1.6 on 2025-02-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("description", models.TextField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=2)),
                ("stock", models.IntegerField()),
            ],
        ),
    ]
